/**
 * Legislative chamber diagrams — ported from the game.
 *
 * The game already renders both of these (`src/lib/charts/westminsterParliament.ts`
 * and `src/lib/charts/parliamentChart.ts` in AHDGame). This is a port of that
 * code, not a reimplementation, so a chamber in Discord and the same chamber on
 * ahousedividedgame.com are the same picture. If the game's sizing tiers or
 * seating rules change, change them here too.
 *
 * Two shapes, because real chambers have two shapes:
 *
 *   WESTMINSTER — the Commons. Two facing banks of benches with crossbenches
 *          off to one side, generated by `westminster-svg` (the same library
 *          the game uses) and rasterised. Not a hemicycle: the entire point of
 *          the chamber's geometry is that Government and Opposition face each
 *          other across the floor.
 *
 *   ARCH — Congress, the Bundestag, the Dáil, the Diet, the NPC. A hemicycle,
 *          using the game's shared sizing tiers so a 100-seat Senate and a
 *          2,980-seat NPC both fit.
 */

import generate from "westminster-svg";
import { toHtml } from "hast-util-to-html";
import { loadImage, type CanvasRenderingContext2D, type Image } from "canvas";
import { chromeHeight, drawEmptyState, ellipsize, renderCard, roundRect, type CardSpec, type Rect } from "./card.js";
import { font } from "./fonts.js";
import { AXIS, INK, STATUS, SURFACE, TYPE, alpha, ensureVisible } from "./theme.js";

export type ChamberShape = "arch" | "westminster";

export interface ChamberParty {
  name: string;
  seats: number;
  /** The party's own colour. Identity — never assigned by rank. */
  color: string;
}

export interface ChamberOptions extends Omit<CardSpec, "height"> {
  parties: ChamberParty[];
  totalSeats: number;
  /** Seats needed to govern. Defaults to a simple majority. */
  majority?: number;
  shape?: ChamberShape;
  /** Overrides the derived split, when the game knows the actual government. */
  governmentPartyNames?: string[];
  emptyMessage?: string;
}

const PAD = 16;
const LEGEND_ROW_H = 17;
const LEGEND_COLS = 3;
const LEGEND_GAP = 18;
const HEADER_H = 52;
/** The game's vacant-seat grey. */
const VACANT = "#3b3d4d";

// ───────────────────────────────────────────────────────────────────────────
// Hemicycle geometry — ported from AHDGame `src/lib/charts/parliamentSizing.ts`
// ───────────────────────────────────────────────────────────────────────────

export interface ParliamentSizing {
  dotR: number;
  rowGap: number;
  innerR: number;
}

/**
 * Tier sizing, in the game's base 400-unit viewBox. The breakpoints are the
 * game's: the US Senate (100) keeps large dots, the Commons (650) and the
 * Bundestag (736) share a tier, and the NPC (2,980) still fits.
 */
export function getParliamentSizing(total: number): ParliamentSizing {
  if (total <= 110) return { dotR: 7, rowGap: 20, innerR: 55 };
  if (total <= 200) return { dotR: 5, rowGap: 14, innerR: 50 };
  if (total <= 750) return { dotR: 3.4, rowGap: 10, innerR: 45 };
  if (total <= 1500) return { dotR: 2.2, rowGap: 6.5, innerR: 38 };
  return { dotR: 1.6, rowGap: 4.5, innerR: 33 };
}

/** Row-packing loop, ported verbatim so radii match the game's. */
export function computeRowRadii(sizing: ParliamentSizing, total: number): { rowRadii: number[]; outerR: number } {
  const minGap = sizing.dotR * 2.4;
  const rowRadii: number[] = [];
  let totalCap = 0;
  for (let row = 0; totalCap < total; row++) {
    const r = sizing.innerR + row * sizing.rowGap;
    const cap = Math.max(1, Math.floor((Math.PI * r) / minGap));
    rowRadii.push(r);
    totalCap += cap;
  }
  const outerR = rowRadii.length === 0 ? sizing.innerR : rowRadii[rowRadii.length - 1];
  return { rowRadii, outerR };
}

export interface ArchSeat {
  x: number;
  y: number;
  /** 0 at the far left, 1 at the far right. */
  t: number;
}

/**
 * Hemicycle dot positions in the game's 400-unit space, centred on (200, 195).
 * Seats are distributed across rows in proportion to arc length, then sorted
 * left to right — the same order the game seats parties in.
 */
export function archLayout(total: number): { seats: ArchSeat[]; outerR: number } {
  if (total <= 0) return { seats: [], outerR: 0 };

  const sizing = getParliamentSizing(total);
  const { rowRadii, outerR } = computeRowRadii(sizing, total);

  const totalArc = rowRadii.reduce((s, r) => s + Math.PI * r, 0);
  const rowSeats: number[] = [];
  let remaining = total;
  for (let i = 0; i < rowRadii.length; i++) {
    if (i === rowRadii.length - 1) {
      rowSeats.push(remaining);
    } else {
      const n = Math.round(((Math.PI * rowRadii[i]) / totalArc) * total);
      const capped = Math.min(n, remaining);
      rowSeats.push(capped);
      remaining -= capped;
    }
  }

  const seats: ArchSeat[] = [];
  for (let row = 0; row < rowRadii.length; row++) {
    const r = rowRadii[row];
    const n = rowSeats[row];
    for (let i = 0; i < n; i++) {
      const t = n > 1 ? i / (n - 1) : 0.5;
      const angle = Math.PI * (1 - t);
      seats.push({ x: 200 + r * Math.cos(angle), y: 195 - r * Math.sin(angle), t });
    }
  }
  seats.sort((a, b) => a.t - b.t);
  return { seats, outerR };
}

// ───────────────────────────────────────────────────────────────────────────
// Westminster — ported from AHDGame `src/lib/charts/westminsterParliament.ts`
// ───────────────────────────────────────────────────────────────────────────

type WestminsterSide = Record<string, { seats: number; colour: string }>;

export interface WestminsterParliament {
  headBench: WestminsterSide;
  left: WestminsterSide;
  right: WestminsterSide;
  crossBench: WestminsterSide;
}

/**
 * Build the `westminster-svg` parliament object.
 *
 * Government sits on the right, as in the real chamber; the two largest
 * remaining parties form the Opposition on the left; everything else — plus any
 * vacant seats — goes to the crossbenches. That is the game's government-mode
 * seating, applied with the only signal the bot has: seat count.
 */
export function buildWestminsterParliament(
  parties: ChamberParty[],
  totalSeats: number,
  governmentPartyNames?: string[],
): WestminsterParliament {
  const sorted = [...parties].sort((a, b) => b.seats - a.seats);
  const filled = sorted.reduce((s, p) => s + p.seats, 0);
  const vacant = Math.max(0, totalSeats - filled);

  const gov = new Set(
    governmentPartyNames?.length ? governmentPartyNames : sorted.slice(0, 1).map((p) => p.name),
  );
  const government = sorted.filter((p) => gov.has(p.name));
  const rest = sorted.filter((p) => !gov.has(p.name));

  const side = (ps: ChamberParty[]): WestminsterSide =>
    Object.fromEntries(ps.map((p) => [p.name, { seats: p.seats, colour: ensureVisible(p.color) }]));

  const crossBench = side(rest.slice(2));
  if (vacant > 0) crossBench.__vacant__ = { seats: vacant, colour: VACANT };

  return { headBench: {}, left: side(rest.slice(0, 2)), right: side(government), crossBench };
}

/**
 * Rasterise a `westminster-svg` diagram.
 *
 * The library emits a `viewBox` with no width/height, which node-canvas refuses
 * to decode ("Width and height must be set on the svg element"), so the root
 * gets explicit dimensions derived from the viewBox aspect ratio.
 */
export async function renderWestminsterImage(
  parliament: WestminsterParliament,
  width: number,
): Promise<Image | null> {
  try {
    let svg = toHtml(generate(parliament) as never);
    const vb = svg.match(/viewBox="([-\d.,\s]+)"/);
    if (!vb) return null;
    const parts = vb[1].split(/[,\s]+/).map(Number);
    const vw = parts[2];
    const vh = parts[3];
    if (!vw || !vh) return null;
    const height = Math.max(1, Math.round((width * vh) / vw));
    svg = svg.replace("<svg ", `<svg width="${width}" height="${height}" `);
    return await loadImage(Buffer.from(svg));
  } catch {
    return null;
  }
}

/** Split the chamber into its two benches, largest party first. */
export function splitBenches(
  parties: ChamberParty[],
  governmentPartyNames?: string[],
): { government: ChamberParty[]; opposition: ChamberParty[] } {
  const sorted = [...parties].sort((a, b) => b.seats - a.seats);
  if (governmentPartyNames?.length) {
    const gov = new Set(governmentPartyNames);
    return {
      government: sorted.filter((p) => gov.has(p.name)),
      opposition: sorted.filter((p) => !gov.has(p.name)),
    };
  }
  return { government: sorted.slice(0, 1), opposition: sorted.slice(1) };
}

// ───────────────────────────────────────────────────────────────────────────
// Rendering
// ───────────────────────────────────────────────────────────────────────────

export function chamberHeight(partyCount: number, shape: ChamberShape, spec: Pick<CardSpec, "subtitle">): number {
  const legendRows = Math.ceil(Math.max(1, partyCount) / LEGEND_COLS);
  const body = shape === "westminster" ? 250 : 226;
  return Math.round(
    chromeHeight({ ...spec, footerLeft: " " }) + HEADER_H + body + legendRows * LEGEND_ROW_H + LEGEND_GAP + PAD * 2,
  );
}

/**
 * Render a chamber card.
 *
 * Async because the Westminster path rasterises an SVG; the arch path draws
 * directly. Both go through the same card chrome.
 */
export async function renderChamber(options: ChamberOptions): Promise<Buffer> {
  const parties = options.parties.filter((p) => p.seats > 0);
  const shape = options.shape ?? "arch";
  const width = options.width ?? 680;
  const height = chamberHeight(parties.length, shape, options);

  const drawn = parties.reduce((s, p) => s + p.seats, 0);
  const total = Math.max(options.totalSeats, drawn);

  // Rasterise before entering the synchronous card renderer.
  const benchImage =
    shape === "westminster" && parties.length > 0
      ? await renderWestminsterImage(buildWestminsterParliament(parties, total, options.governmentPartyNames), 1400)
      : null;

  return renderCard({ ...options, width, height }, (ctx, plot) => {
    if (parties.length === 0) {
      drawEmptyState(ctx, plot, options.emptyMessage ?? "No seat data for this chamber.");
      return;
    }
    draw(ctx, plot, parties, shape, total, benchImage, options);
  });
}

function draw(
  ctx: CanvasRenderingContext2D,
  plot: Rect,
  parties: ChamberParty[],
  shape: ChamberShape,
  total: number,
  benchImage: Image | null,
  options: ChamberOptions,
): void {
  const majority = options.majority ?? Math.floor(total / 2) + 1;
  const { government, opposition } = splitBenches(parties, options.governmentPartyNames);
  const govSeats = government.reduce((s, p) => s + p.seats, 0);
  const oppSeats = opposition.reduce((s, p) => s + p.seats, 0);
  const clears = govSeats >= majority;

  const legendRows = Math.ceil(parties.length / LEGEND_COLS);
  const area: Rect = {
    x: plot.x + PAD,
    y: plot.y + PAD + HEADER_H,
    w: plot.w - PAD * 2,
    h: plot.h - PAD * 2 - HEADER_H - legendRows * LEGEND_ROW_H - LEGEND_GAP,
  };

  if (shape === "westminster") {
    drawWestminster(ctx, area, benchImage);
  } else {
    drawArch(ctx, area, parties, total, majority);
  }

  drawHeader(ctx, plot, { govSeats, oppSeats, total, clears });
  drawVerdict(ctx, plot, area, shape, { clears, majority, govSeats });
  drawLegend(ctx, plot, parties, total, legendRows);
}

/** Composite the rasterised chamber, letterboxed into the plot area. */
function drawWestminster(ctx: CanvasRenderingContext2D, area: Rect, image: Image | null): void {
  if (!image || !image.width || !image.height) {
    drawEmptyState(ctx, area, "Chamber diagram unavailable.");
    return;
  }
  const scale = Math.min(area.w / image.width, area.h / image.height);
  const w = image.width * scale;
  const h = image.height * scale;
  ctx.drawImage(image, area.x + (area.w - w) / 2, area.y + (area.h - h) / 2, w, h);
}

/** Hemicycle, drawn natively so it stays crisp and picks up the house style. */
function drawArch(
  ctx: CanvasRenderingContext2D,
  area: Rect,
  parties: ChamberParty[],
  total: number,
  majority: number,
): void {
  const { seats, outerR } = archLayout(total);
  if (seats.length === 0) return;

  // Game space is 400 wide, centred on (200, 195); fit that arc into the plot.
  const scale = Math.min(area.w / (outerR * 2 + 12), area.h / (outerR + 12));
  const cx = area.x + area.w / 2;
  const cy = area.y + (area.h + outerR * scale) / 2;
  const px = (x: number) => cx + (x - 200) * scale;
  const py = (y: number) => cy + (y - 195) * scale;
  const dotR = Math.max(1, getParliamentSizing(total).dotR * scale * 0.92);

  const colors: string[] = [];
  for (const party of [...parties].sort((a, b) => b.seats - a.seats)) {
    const color = ensureVisible(party.color);
    for (let i = 0; i < party.seats; i++) colors.push(color);
  }

  seats.forEach((seat, i) => {
    ctx.beginPath();
    ctx.arc(px(seat.x), py(seat.y), dotR, 0, Math.PI * 2);
    ctx.fillStyle = colors[i] ?? VACANT;
    ctx.fill();
  });

  // The half-way line, as the game draws it
  ctx.strokeStyle = AXIS.baseline;
  ctx.lineWidth = 1;
  ctx.setLineDash([4, 3]);
  ctx.beginPath();
  ctx.moveTo(cx, py(195 - outerR) - 8);
  ctx.lineTo(cx, py(195) + 2);
  ctx.stroke();
  ctx.setLineDash([]);

  // Ring the seat where the majority actually falls
  const marker = seats[Math.min(seats.length - 1, majority - 1)];
  if (marker) {
    ctx.strokeStyle = alpha(INK.primary, 0.6);
    ctx.lineWidth = 1.4;
    ctx.beginPath();
    ctx.arc(px(marker.x), py(marker.y), dotR + 3.5, 0, Math.PI * 2);
    ctx.stroke();
  }

  ctx.font = font(500, 9, "mono");
  ctx.fillStyle = INK.muted;
  ctx.textAlign = "left";
  ctx.fillText("◄ LEFT", area.x, py(195) + 10);
  ctx.textAlign = "right";
  ctx.fillText("RIGHT ►", area.x + area.w, py(195) + 10);
  ctx.textAlign = "left";
}

function drawHeader(
  ctx: CanvasRenderingContext2D,
  plot: Rect,
  d: { govSeats: number; oppSeats: number; total: number; clears: boolean },
): void {
  const x0 = plot.x + PAD;
  const x1 = plot.x + plot.w - PAD;
  const y = plot.y + PAD;

  ctx.font = font(600, 9.5, "mono");
  ctx.fillStyle = INK.muted;
  ctx.textAlign = "left";
  ctx.fillText(d.clears ? "GOVERNMENT" : "LARGEST PARTY", x0, y + 9);
  ctx.textAlign = "right";
  ctx.fillText(d.clears ? "OPPOSITION" : "OTHER PARTIES", x1, y + 9);

  ctx.font = font(700, 22, "mono");
  ctx.fillStyle = INK.primary;
  ctx.textAlign = "left";
  ctx.fillText(String(d.govSeats), x0, y + 33);
  ctx.textAlign = "right";
  ctx.fillText(String(d.oppSeats), x1, y + 33);

  ctx.font = font(500, 9, "mono");
  ctx.fillStyle = INK.muted;
  ctx.textAlign = "left";
  ctx.fillText(`of ${d.total}`, x0, y + 45);
  ctx.textAlign = "right";
  ctx.fillText(`of ${d.total}`, x1, y + 45);
  ctx.textAlign = "left";
}

function drawVerdict(
  ctx: CanvasRenderingContext2D,
  plot: Rect,
  area: Rect,
  shape: ChamberShape,
  d: { clears: boolean; majority: number; govSeats: number },
): void {
  const verdict = d.clears ? "MAJORITY" : `HUNG · ${d.majority - d.govSeats} SHORT`;
  const accent = d.clears ? STATUS.good : STATUS.critical;

  // Westminster fills its frame, so the verdict sits between the counts in the
  // header; the arch leaves its centre empty, which is where it belongs there.
  const cx = plot.x + plot.w / 2;
  const cy = shape === "westminster" ? plot.y + PAD + 26 : area.y + area.h - 24;

  ctx.textAlign = "center";
  ctx.font = font(600, 10, "mono");
  const w = ctx.measureText(verdict).width;
  ctx.fillStyle = SURFACE.plot;
  roundRect(ctx, cx - w / 2 - 10, cy - 13, w + 20, 20, 10);
  ctx.fill();
  ctx.fillStyle = alpha(accent, 0.2);
  roundRect(ctx, cx - w / 2 - 8, cy - 11.5, w + 16, 17, 8.5);
  ctx.fill();
  ctx.fillStyle = accent;
  ctx.fillText(verdict, cx, cy + 1);

  ctx.font = font(500, 9, "mono");
  ctx.fillStyle = INK.muted;
  ctx.fillText(`${d.majority} to govern`, cx, cy + 16);
  ctx.textAlign = "left";
}

/**
 * Legend below the chamber. Always present, and every entry carries its seat
 * count and share in text, so identity never rests on colour alone.
 */
function drawLegend(
  ctx: CanvasRenderingContext2D,
  plot: Rect,
  parties: ChamberParty[],
  total: number,
  legendRows: number,
): void {
  const x0 = plot.x + PAD;
  const w = plot.w - PAD * 2;
  const colW = w / LEGEND_COLS;
  const y0 = plot.y + plot.h - PAD - legendRows * LEGEND_ROW_H + LEGEND_ROW_H * 0.72;

  [...parties]
    .sort((a, b) => b.seats - a.seats)
    .forEach((party, i) => {
      const col = i % LEGEND_COLS;
      const row = Math.floor(i / LEGEND_COLS);
      const x = x0 + col * colW;
      const y = y0 + row * LEGEND_ROW_H;

      ctx.fillStyle = ensureVisible(party.color);
      roundRect(ctx, x, y - 7.5, 9, 9, 2.5);
      ctx.fill();

      const share = total > 0 ? ` · ${((party.seats / total) * 100).toFixed(1)}%` : "";
      ctx.font = font(500, TYPE.footer, "mono");
      const metaW = ctx.measureText(`${party.seats}${share}`).width;

      ctx.font = font(500, TYPE.label);
      ctx.fillStyle = INK.primary;
      const name = ellipsize(ctx, party.name, colW - 22 - metaW - 10);
      ctx.fillText(name, x + 15, y);
      const nameW = ctx.measureText(name).width;

      ctx.font = font(500, TYPE.footer, "mono");
      ctx.fillStyle = INK.muted;
      ctx.fillText(`${party.seats}${share}`, x + 15 + nameW + 7, y);
    });
}
